// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tables-screen/ActionList.tsx": () => import("../components/mockups/tables-screen/ActionList.tsx"),
  "./components/mockups/tables-screen/DenseGrid.tsx": () => import("../components/mockups/tables-screen/DenseGrid.tsx"),
  "./components/mockups/tables-screen/FloorMap.tsx": () => import("../components/mockups/tables-screen/FloorMap.tsx")
};
